# Generated by Django 2.1.2 on 2019-03-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_auto_20190313_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
